Class.getName
.io
junit.run
junit.TestRunner
JUnitTestRunner.ERRORS
JUnitTestRunner.FAILURES
JUnitTestRunner.SUCCESS
junit.textui
.OutputStream
ResultFormatter.getClassLoader
String.indexOf
StringWriter.toString
TestRunner.getError
TestRunner.getFormatter
TestRunner.getRetCode
TestRunner.run
Throwable.printStackTrace
