BufferedReader.readLine
ExecuteWatchdog.killedProcess
ExecuteWatchdog.start
ExecuteWatchdog.stop
File.pathSeparator
File.separator
JavaEnvUtils.getJreExecutable
JavaEnvUtils.isJavaVersion
JavaEnvUtils.JAVA_1_1
Process.exitValue
Process.getErrorStream
Process.waitFor
Runtime.exec
Runtime.getRuntime
StringBuffer.append
StringBuffer.toString
String.length
String.valueOf
System.currentTimeMillis
System.err
System.getProperty
System.println
Thread.join
Thread.start
TimeProcess.getName
