FileUtils.newFileUtils
FileUtils.normalize
.getAbsolutePath
.isAbsolute
JavaEnvUtils.getJavaVersion
JavaEnvUtils.getJdkExecutable
JavaEnvUtils.getJreExecutable
JavaEnvUtils.JAVA_1_0
JavaEnvUtils.JAVA_1_1
Os.isFamily
Os.isName
String.endsWith
String.equals
String.startsWith
System.getProperty
