BasedirChecker.getError
BuildEvent.getAbsolutePath
BuildEvent.getBaseDir
BuildEvent.getInputHandler
BuildEvent.getProject
BuildEvent.getProperty
BuildEvent.getReference
.equals
.exists
File.getAbsolutePath
File.length
.getName
getProject.addBuildListener
getProjectDir.getAbsolutePath
getProject.removeBuildListener
getProject.resolveFile
getProject.setInputHandler
getProject.setUserProperty
InputHandlerChecker.getError
Path.createPath
Path.list
Path.setPath
Path.setProject
Path.systemClasspath
Path.toString
project.addBuildListener
project.addReference
project.removeBuildListener
project.resolveFile
PropertyChecker.getError
ReferenceChecker.getError
String.length
System.getProperty
this.expectedValues
this.expectSame
this.key
this.keys
this.value
